config/routes.rb
Rails.application.routes.draw do


  # resources :comments
  # resources :posts
  # resources :drinks
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Add a root route if you don't have one...
    # We can use users#new for now, or replace this with the controller and action you want to be the site root:
    root to: 'users#new'
    # sign up page with form:
    get 'users/new' => 'users#new', as: :new_user
    # create (post) action for when sign up form is submitted:
    post 'users' => 'users#create'
    # get 'users/:id' => 'users#show', as: :user
    # get 'users/index' => 'users#show' as: :user
    # sessions
    # log in page with form:
    get '/login'     => 'sessions#new'
    # create (post) action for when log in form is submitted:
    post '/login'    => 'sessions#create'
    # delete action to log out:
    delete '/logout' => 'sessions#destroy'
    get 'pages/secret'

    # drinks load page

    get 'drinks/' => 'drinks#index'
    post 'drinks/' => 'drinks#create'
    get 'drinks/new' => 'drinks#new', as: :new_drink
    get 'drinks/:id' => 'drinks#show', as: :drink
    get 'drinks/:id/edit' => 'drinks#edit', as: :edit_drink
    patch 'drinks/:id' => 'drinks#update'
    delete 'drinks/:id' => 'drinks#destroy'

    get 'posts/' => 'posts#index'
    post 'posts/' => 'posts#create'
    get 'posts/new' => 'posts#new', as: :new_post
    get 'posts/:id' => 'posts#show', as: :post
    get 'posts/:id/edit' => 'posts#edit', as: :edit_post
    patch 'posts/:id' => 'posts#update'
    delete 'posts/:id' => 'posts#destroy'


    get 'orders/' => 'orders#index'
    post 'orders' => 'orders#create'
    get 'orders/new' => 'orders#new', as: :new_order
    get 'orders/:id' => 'orders#show', as: :order
    get 'orders/:id/edit' => 'orders#edit', as: :edit_order
    patch 'orders/:id' => 'orders#update'
    delete 'orders/:id' => 'orders#destroy'


    get 'comments/' => 'comments#index'
    post 'comments/' => 'comments#create'
    get 'comments/new' => 'comments#new', as: :new_comment
    get 'comments/:id' => 'comments#show', as: :comment
    get 'comments/:id/edit' => 'comments#edit', as: :edit_comment
    patch 'comments/:id' => 'comments#update'
    delete 'comments/:id' => 'comments#destroy'

end

app/views/partials/_main.html.erb
<div class="jumbotron">
  <h1><img src= "https://github.com/timseo/regrets/blob/master/image/regrets-logo-black.png?raw=true" alt= "regrets" class= "img_responsive" ></h1>
  <p>Ever have a great night out and wonder the morning after what exactly was the perfect mix of libations that created such a magical evening out?  Regrets provides a place for you to keep track and share your tab.</p>
  <p>
    <a>
      <% if current_user %>
        <!-- current_user will return true if a user is logged in -->
        <%= "Hello #{current_user.name.capitalize!}" %>
      <br>
        <a href= "/posts" class="btn btn-primary btn-lg" >Recent Regrets</a>

        <!-- not logged in -->
      <% else %>
        <a href= "/" class="btn btn-primary btn-lg">Sign up</a>

      <% end %>
    </a>




  </p>

</div>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <img src= "https://github.com/timseo/regrets/blob/master/image/regrets-logo-white.png?raw=true" alt= "regrets" class= "img_responsive" height= '30px' >
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <ul class="nav navbar-nav navbar-right">
        <li><a href="https://timseo.github.io/GA_project1/">sloPPy Dice</a></li>
        <li><a href="/">Home</a></li>
        <li><a href="/drinks">Drinks</a></li>
        <li><a href="/posts">Posts</a></li>
        <li><a>

            </a>
        </li>







        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Members Only   <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li>
              <a>
                <% if current_user %>
                  <!-- current_user will return true if a user is logged in -->
                  <%= "Logged in as #{current_user.name}" %>
                  <%= link_to 'Post', posts_path %>
                  <%= link_to 'Log Out', logout_path, method: :delete %>
                <% else %>
                  <!-- not logged in -->
                  <%= link_to 'Home', root_path %>
                  <%= link_to 'Log In', login_path %>
                  <%= link_to 'Sign Up', new_user_path %>
                <% end %>
              </a>
            </li>
            <!-- <li><a href="#">Another action</a></li> -->
            <!-- <li><a href="#">Something else here</a></li> -->
            <!-- <li role="separator" class="divider"></li> -->
            <!-- <li><a href="#">Separated link</a></li> -->
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>